### ISSUE TITLE
limiting the extent

### ISSUE THREAD

**Issue by danhammer** [Vizzuality/surface-water#7]
We run into problems when the area of the user-drawn box is somewhere above 300,000ha.  Is it possible to add this to the error message -- before the user waits for a few seconds?  Specifically, if the drawn box is greater than 300,000ha, then an error is thrown immediately, asking the user to supply a smaller area?

**Comment by clementprdhomme** [comment]
Good morning Dan,

I've pushed the changes to `master` and it's available online too.

Clément
